Colab is making it easier than ever to integrate powerful Generative AI capabilities into your projects. We are launching public preview for a simple and intuitive Python library (google.colab.ai) to access state-of-the-art language models directly within Colab environments. All users have free access to most popular LLMs, while paid users have access to a wider selection of models. This means users can spend less time on configuration and set up and more time bringing their ideas to life. With just a few lines of code, you can now perform a variety of tasks:
- Generate text
- Translate languages
- Write creative content
- Categorize text

Happy Coding!


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Getting_started_with_google_colab_ai.ipynb)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Choosing a Model
The model names give you a hint about their capabilities and intended use:

Pro: These are the most capable models, ideal for complex reasoning, creative tasks, and detailed analysis.

Flash: These models are optimized for high speed and efficiency, making them great for summarization, chat applications, and tasks requiring rapid responses.

Gemma: These are lightweight, open-weight models suitable for a variety of text generation tasks and are great for experimentation.

In [2]:
import os

drive_path = "/content/drive/MyDrive/cyber_project"
os.makedirs(drive_path, exist_ok=True)

print("Folder ready:", drive_path)

Folder ready: /content/drive/MyDrive/cyber_project

In [3]:
import urllib.request

url = "https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTrain+.txt"
save_path = "/content/drive/MyDrive/cyber_project/KDDTrain.txt"

urllib.request.urlretrieve(url, save_path)

print("Dataset downloaded to:", save_path)

Dataset downloaded to: /content/drive/MyDrive/cyber_project/KDDTrain.txt

For longer text generations, you can stream the response. This displays the output token by token as it's generated, rather than waiting for the entire response to complete. This provides a more interactive and responsive experience. To enable this, simply set stream=True.

In [4]:
import pandas as pd

file_path = "/content/drive/MyDrive/cyber_project/KDDTrain.txt"

df = pd.read_csv(file_path, header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [5]:
clean_path = "/content/drive/MyDrive/cyber_project/clean_data.csv"
df.to_csv(clean_path, index=False)

print("Clean dataset saved to Drive!")

Clean dataset saved to Drive!

In [6]:
columns = [
    "duration","protocol_type","service","flag","src_bytes","dst_bytes",
    "land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted",
    "num_root","num_file_creations","num_shells","num_access_files",
    "num_outbound_cmds","is_host_login","is_guest_login","count",
    "srv_count","serror_rate","srv_serror_rate","rerror_rate",
    "srv_rerror_rate","same_srv_rate","diff_srv_rate",
    "srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate","dst_host_srv_diff_host_rate",
    "dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate",
    "label","difficulty"
]

df.columns = columns
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

Warning: Total number of columns (43) exceeds max_columns (20) limiting to first (20) columns.

In [7]:
df['attack'] = df['label'].apply(lambda x: 0 if x == 'normal' else 1)
df[['label','attack']].head()

     label  attack
0   normal       0
1   normal       0
2  neptune       1
3   normal       0
4   normal       0

In [8]:
df['src_ip'] = "src_" + df.index.astype(str)
df['dst_ip'] = "dst_" + df.index.astype(str)

In [9]:
df['src_ip'] = df['protocol_type'] + "_" + df['service']
df['dst_ip'] = df['flag']

In [10]:
df_sample = df.sample(n=5000, random_state=42)

In [11]:
processed_path = "/content/drive/MyDrive/cyber_project/processed_data.csv"
df_sample.to_csv(processed_path, index=False)

print("Processed data saved!")

Processed data saved!

In [12]:
graph_data = df_sample[['src_ip','dst_ip','attack']]
graph_data.head()

             src_ip dst_ip  attack
378    udp_domain_u     SF       0
32038      tcp_http     S0       1
86399     tcp_pop_3     S0       1
74412   tcp_private    REJ       1
52951   tcp_private   RSTR       1

In [14]:
!pip install neo4j

Collecting neo4j
  Downloading neo4j-6.1.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from neo4j) (2025.2)
Downloading neo4j-6.1.0-py3-none-any.whl (325 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.3/325.3 kB 17.1 MB/s eta 0:00:00
Installing collected packages: neo4j
Successfully installed neo4j-6.1.0

In [15]:
from neo4j import GraphDatabase

uri = "neo4j+s://09631995.databases.neo4j.io"
username = "neo4j"
password = "ro8yR_zKYuU2MGKXYMXA3BuIZkxi3ip7e2u3CHY-CjY"   # after reset

driver = GraphDatabase.driver(uri, auth=(username, password))

# Test connection
with driver.session() as session:
    result = session.run("RETURN 1 AS test")
    print(result.single()["test"])

1

In [16]:
def create_graph(tx, src, dst, attack):
    query = """
    MERGE (a:Device {id: $src})
    MERGE (b:Device {id: $dst})
    MERGE (a)-[r:CONNECTS]->(b)
    SET r.attack = $attack
    """
    tx.run(query, src=src, dst=dst, attack=attack)


with driver.session() as session:
    for _, row in graph_data.iterrows():
        session.execute_write(
            create_graph,
            row['src_ip'],
            row['dst_ip'],
            row['attack']
        )

In [17]:
query = """
MATCH (a)-[r]->(b)
RETURN a, r, b
LIMIT 50
"""

with driver.session() as session:
    result = session.run(query)
    for record in result:
        print(record)

<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:0' labels=frozenset({'Device'}) properties={'id': 'udp_domain_u'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846976' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:0' labels=frozenset({'Device'}) properties={'id': 'udp_domain_u'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532226' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846978' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1157425104234217474' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:6' labels=frozenset({'Device'}) properties={'id': 'REJ'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:6' labels=frozenset({'Device'}) properties={'id': 'REJ'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1161928703861587970' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:7' labels=frozenset({'Device'}) properties={'id': 'RSTR'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:7' labels=frozenset({'Device'}) properties={'id': 'RSTR'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1159676904047902722' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:6917529027641081904' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:48' labels=frozenset({'Device'}) properties={'id': 'S1'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:48' labels=frozenset({'Device'}) properties={'id': 'S1'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:6917529027641081925' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:69' labels=frozenset({'Device'}) properties={'id': 'S2'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:69' labels=frozenset({'Device'}) properties={'id': 'S2'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:6919780827454767175' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:2' labels=frozenset({'Device'}) properties={'id': 'tcp_http'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:71' labels=frozenset({'Device'}) properties={'id': 'S3'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:71' labels=frozenset({'Device'}) properties={'id': 'S3'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:4' labels=frozenset({'Device'}) properties={'id': 'tcp_pop_3'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532228' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:4' labels=frozenset({'Device'}) properties={'id': 'tcp_pop_3'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:4' labels=frozenset({'Device'}) properties={'id': 'tcp_pop_3'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846980' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:4' labels=frozenset({'Device'}) properties={'id': 'tcp_pop_3'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1157425104234217477' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532229' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846981' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:6' labels=frozenset({'Device'}) properties={'id': 'REJ'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:6' labels=frozenset({'Device'}) properties={'id': 'REJ'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:6917529027641081863' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:7' labels=frozenset({'Device'}) properties={'id': 'RSTR'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:7' labels=frozenset({'Device'}) properties={'id': 'RSTR'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:6917529027641081878' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:22' labels=frozenset({'Device'}) properties={'id': 'SH'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:22' labels=frozenset({'Device'}) properties={'id': 'SH'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1159676904047902725' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:6919780827454767176' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:5' labels=frozenset({'Device'}) properties={'id': 'tcp_private'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:72' labels=frozenset({'Device'}) properties={'id': 'RSTOS0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:72' labels=frozenset({'Device'}) properties={'id': 'RSTOS0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:8' labels=frozenset({'Device'}) properties={'id': 'tcp_iso_tsap'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532232' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:8' labels=frozenset({'Device'}) properties={'id': 'tcp_iso_tsap'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:8' labels=frozenset({'Device'}) properties={'id': 'tcp_iso_tsap'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846984' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:8' labels=frozenset({'Device'}) properties={'id': 'tcp_iso_tsap'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:6' labels=frozenset({'Device'}) properties={'id': 'REJ'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:6' labels=frozenset({'Device'}) properties={'id': 'REJ'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846985' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532233' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1157425104234217481' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1161928703861587977' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:48' labels=frozenset({'Device'}) properties={'id': 'S1'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:48' labels=frozenset({'Device'}) properties={'id': 'S1'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1159676904047902729' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:9' labels=frozenset({'Device'}) properties={'id': 'tcp_smtp'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:69' labels=frozenset({'Device'}) properties={'id': 'S2'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:69' labels=frozenset({'Device'}) properties={'id': 'S2'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:10' labels=frozenset({'Device'}) properties={'id': 'tcp_exec'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846986' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:10' labels=frozenset({'Device'}) properties={'id': 'tcp_exec'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:10' labels=frozenset({'Device'}) properties={'id': 'tcp_exec'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532234' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:10' labels=frozenset({'Device'}) properties={'id': 'tcp_exec'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1157425104234217483' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:1' labels=frozenset({'Device'}) properties={'id': 'SF'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1152921504606846987' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>) type='CONNECTS' properties={'attack': 1}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:3' labels=frozenset({'Device'}) properties={'id': 'S0'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1161928703861587979' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:7' labels=frozenset({'Device'}) properties={'id': 'RSTR'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:7' labels=frozenset({'Device'}) properties={'id': 'RSTR'}>>
<Record a=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}> r=<Relationship element_id='5:5d9259a2-b41c-477f-980b-4629ebf576e2:1155173304420532235' nodes=(<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:11' labels=frozenset({'Device'}) properties={'id': 'tcp_telnet'}>, <Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>) type='CONNECTS' properties={'attack': 0}> b=<Node element_id='4:5d9259a2-b41c-477f-980b-4629ebf576e2:31' labels=frozenset({'Device'}) properties={'id': 'RSTO'}>>